SingularityBdWeb/ViewComponents/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SingularitybdWeb.Services;
using System.Linq;
using System.Threading.Tasks;

namespace SingularitybdWeb.ViewComponents
{
	public class NavigationMenuViewComponent : ViewComponent
	{
		private readonly IDataAccessService _dataAccessService;

		public NavigationMenuViewComponent(IDataAccessService dataAccessService)
		{
			_dataAccessService = dataAccessService;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var items = await _dataAccessService.GetMenuItemsAsync(HttpContext.User);

			items = items.Distinct(new ItemEqualityComparer()).ToList();
			return View(items);
		}
	}
}

SingularityBdWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - SingularitybdWeb</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<style>
		input[type=checkbox] {
			-ms-transform: scale(2);
			-moz-transform: scale(2);
			-webkit-transform: scale(2);
			-o-transform: scale(2);
			transform: scale(2);
			padding: 10px;
		}
	</style>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
			@await Component.InvokeAsync("NavigationMenu")
		</nav>
	</header>
	<br />
	<br />
	<div style="margin-top: 50px;" class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>
	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2020 - Dynamic Role Authorization - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>